```{r}

library(Lahman)
library(dplyr)
library(ggplot2)
library(gridExtra)

```

```{r}

#General

teams_data = Teams %>%
  filter(yearID>=1900) %>% #data before 1900 seems very irregular/lots of missing data
  group_by(yearID) %>%
  summarize(Total_G = sum(G),
            
            Total_SB = sum(SB),
            SB_per_G = sum(SB)/sum(G),
            
            Total_HR = sum(HR),
            HR_per_G = sum(HR)/sum(G),
            
            Total_X3B = sum(X3B),
            X3B_per_G = sum(X3B)/sum(G),)

plot1 = ggplot(data = teams_data, aes(x=yearID, y=SB_per_G))+
  geom_point()+
  geom_smooth()+
  xlab("year")+
  ylab("avg SB per game")+
  ggtitle("A (1.4)")+
  theme_bw(base_size = 11)

plot2 = ggplot(data = teams_data, aes(x=yearID, y=HR_per_G))+
  geom_point()+
  geom_smooth()+
  xlab("year")+
  ylab("avg HR per game")+
  ggtitle("B (1.2)")+
  theme_bw(base_size = 11)

plot3 = ggplot(data = teams_data, aes(x=yearID, y=X3B_per_G))+
  geom_point()+
  geom_smooth()+
  xlab("year")+
  ylab("avg triples per game")+
  ggtitle("C (1.3)")+
  theme_bw(base_size = 11)

grid.arrange(plot1, plot2, plot3, ncol = 2)

```

```{r}

#National League

teams_data = Teams %>%
  filter(yearID>=1900, lgID == "NL") %>% #data before 1900 seems very irregular/lots of missing data
  group_by(yearID) %>%
  summarize(Total_G = sum(G),
            
            Total_SB = sum(SB),
            SB_per_G = sum(SB)/sum(G),
            
            Total_HR = sum(HR),
            HR_per_G = sum(HR)/sum(G),
            
            Total_X3B = sum(X3B),
            X3B_per_G = sum(X3B)/sum(G),)

plot1 = ggplot(data = teams_data, aes(x=yearID, y=SB_per_G))+
  geom_point()+
  geom_smooth()+
  xlab("year")+
  ylab("avg SB per game")+
  ggtitle("A (1.4)")+
  theme_bw(base_size = 11)

plot2 = ggplot(data = teams_data, aes(x=yearID, y=HR_per_G))+
  geom_point()+
  geom_smooth()+
  xlab("year")+
  ylab("avg HR per game")+
  ggtitle("B (1.2)")+
  theme_bw(base_size = 11)

plot3 = ggplot(data = teams_data, aes(x=yearID, y=X3B_per_G))+
  geom_point()+
  geom_smooth()+
  xlab("year")+
  ylab("avg triples per game")+
  ggtitle("C (1.3)")+
  theme_bw(base_size = 11)

grid.arrange(plot1, plot2, plot3, ncol = 2)

```

```{r}

teams_data = Teams %>%
  filter(yearID>=1900, lgID == "AL") %>% #data before 1900 seems very irregular/lots of missing data
  group_by(yearID) %>%
  summarize(Total_G = sum(G),
            
            Total_SB = sum(SB),
            SB_per_G = sum(SB)/sum(G),
            
            Total_HR = sum(HR),
            HR_per_G = sum(HR)/sum(G),
            
            Total_X3B = sum(X3B),
            X3B_per_G = sum(X3B)/sum(G),)

plot1 = ggplot(data = teams_data, aes(x=yearID, y=SB_per_G))+
  geom_point()+
  geom_smooth()+
  xlab("year")+
  ylab("avg SB per game")+
  ggtitle("A (1.4)")+
  theme_bw(base_size = 11)

plot2 = ggplot(data = teams_data, aes(x=yearID, y=HR_per_G))+
  geom_point()+
  geom_smooth()+
  xlab("year")+
  ylab("avg HR per game")+
  ggtitle("B (1.2)")+
  theme_bw(base_size = 11)

plot3 = ggplot(data = teams_data, aes(x=yearID, y=X3B_per_G))+
  geom_point()+
  geom_smooth()+
  xlab("year")+
  ylab("avg triples per game")+
  ggtitle("C (1.3)")+
  theme_bw(base_size = 11)

grid.arrange(plot1, plot2, plot3, ncol = 2)

```

```{r}

years = c(1900, 1910, 1920, 1930, 1940, 1950, 1960, 1965, 1970, 1980, 1990, 2000, 2010, 2019)

plots1 = list()

for (i in 1:9) {
  
  players_data = Batting %>%
  filter(yearID==years[i]) %>% #data before 1900 seems very irregular/lots of missing data
  mutate(SB_per_G = SB/G) %>%
  group_by(playerID) %>% 
  arrange(desc(SB_per_G)) %>% 
  ungroup() %>% 
  mutate(order = row_number())
  
  firstData = players_data %>%
    filter(SB_per_G == 0)
  first0 = as.numeric(firstData[1,"order"])
  
  xSpacing = first0 + nrow(players_data)/8
  ratio = round(first0/nrow(players_data), 2)

plots1[[i]] = ggplot(data = players_data, aes(x=order, y=SB_per_G))+
  geom_point(size=0.5)+
  geom_vline(xintercept=first0, color="red", linetype="dashed")+
  geom_text(x =  xSpacing, y= 0.35, label = ratio, col="red", size=3.3)+
  ylim(0,0.5)+
  xlab("")+
  ylab("")+
  ggtitle(years[i])+
  theme_bw(base_size = 11)+
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
  
}

do.call("grid.arrange", c(plots1, ncol=floor(sqrt(length(plots1)))))


```

```{r}

teams_data = Teams %>%
  filter(yearID>=1900) %>% #data before 1900 seems very irregular/lots of missing data
  group_by(yearID) %>%
  summarize(Total_G = sum(G),
            
            Total_SB = sum(SB),
            SB_per_G = sum(SB)/sum(G),
            
            Total_CS = sum(CS),
            CS_per_G = sum(CS)/sum(G),
            
            Total_ratio = 100*Total_SB / (Total_SB + Total_CS))

ggplot(data = teams_data, aes(x=yearID, y=Total_ratio))+
  geom_point()+
  geom_smooth()+
  xlab("year")+
  ylab("succes rate of SB (%)")+
  theme_bw(base_size = 11)

```


